### ISSUE TITLE
Ranaldgift site not up to date

### ISSUE THREAD

**Issue by 55JinS77** [ranaldsgift/ranalds.gift#11]
I dont know if it is worth to make an Issue about....But its been months since Vermintide II got a Re-balance patch that changed multiple classes & weapons, and even recently got a hotfix of said patch; Yet there has not been any changes to the site since the patch released.
So I just wanted to warn about this, sorry to bother.

**Comment by ranaldsgift** [comment]
Resolved, thanks!
