### ISSUE TITLE
Implementing a supporting VT2 Mod

### ISSUE THREAD

**Issue by Ogrepleb** [ranaldsgift/ranalds.gift#4]
I'm working on a mod to import builds directly into Vermintide 2.  So far it seems straight forward to parse the URLs from the "Copy URL"  button in the `/heroes` route (I've been reading through repo contents of `src/data`).  However, this functionality doesn't seem to exist for user-created builds, `/builds` (for example https://www.ranalds.gift/build/IYRml4fCJPpNuNTZYL5w/view).  It would be great to have an "export build" button that either 

1) Generates a URL analagous to the functionality in `/heroes`; or
2) Serializes (JSON + base64) the build information (career, weapons, talents, properties and traits) using the game's "code names".  For example `wh_2h_sword` for Saltz's Greatsword or `wh_bountyhunter` for his Bounty Hunter career.

My plan is to have a chat command where users can paste the URL or serialized string, like
```
\loadout https://www.ranalds.gift/heroes/11/312221/38-1-2-1/63-1-2-1/1-2-1/1-2-1/2-3-1
or
\loadout VGhlc2Ugc3RhaXJzIGdvIHVwIQ==
```

**Comment by ranaldsgift** [comment]
Amazing, this is awesome. I can do option 1 very easily, but I think option 2 might be better long term. Just have to ensure all the proper code names are used for the properties and traits, Craven created a script for V2 that would dump all that data, but it's no longer usable. We have the existing data so it should be fine for now. I should have time in the next few weeks to work on this.

**Comment by Ogrepleb** [comment]
Thanks for the quick response! After thinking about at how the JSON schema might look, I think option 1 is actually better from a UX point of view, JSON + base64 messages in chat will be pretty long and clog up chat.  Originally, I thought to use a fully self-describing schema, like 
```json 
{
    "career": "wh_bountyhunter",
    "talents": [1, 2, 3, 3, 1, 2],
    "melee": {
        "weapon": "wh_2h_sword",
        "trait": "Swift Slaying",
        "prop1": "Crit Chance",
        "prop2": "Attack Speed"
    },
    "range": {
        "weapon": "wh_crossbow",
        "trait": "Scrounger",
        "prop1": "Crit Chance",
        "prop2": "Crit Power"
    },
    "necklace": {
        "trait": "Natural Bond",
        "prop1": "Stamina",
        "prop2": "Health"
    },
    "charm": {
        "trait": "Proxy",
        "prop1": "Attack Speed",
        "prop2": "Power vs Skaven"
    },
    "trinket": {
        "trait": "Shrapnel",
        "prop1": "Crit Chance",
        "prop2": "Cooldown Reduction"
    }
}
```
But measuring the length of the encoded string:
```bash
jq -c . build.json | base64 -w 0 | wc -c
640
```
which is much longer than the URL (< 80 characters).  I tried using a compact array-based form:
```json
[
    "wh_bountyhunter",
    [1, 2, 3, 3, 1, 2],
    [
        "wh_2h_sword",
        "Swift Slaying",
        "Crit Chance",
        "Attack Speed"
    ],
    [
        "wh_crossbow",
        "Scrounger",
        "Crit Chance",
        "Crit Power"
    ],
    [
        "Natural Bond",
        "Stamina",
        "Health"
    ],
    [
        "Proxy",
        "Attack Speed",
        "Power vs Skaven"
    ],
    [
        "Shrapnel",
        "Crit Chance",
        "Cooldown Reduction"
    ]
]
```
which when encoded, is still 370 characters long.    Compression doesn't help much either:
```bash
jq -c . build-compact.json | xz -e | base64 -w 0 | wc -c
332
```
Therefore I think the URL is a better choice, especially if it's easier to implement.  To make it less fragile however, I think moving the "maps" (like `WeaponMap.js`, `HeroMap.js` etc) to JSON form, instead of JS literals, is a good idea.  This way, the mod can just parse the JSON directly, so keeping the mod in-sync with Ranald's Gift is easier (just re-download these files from the repo).

**Comment by Ogrepleb** [comment]
I've implemented the mod based on URLs, if you want to give it a try it's on the Steam Workshop [here](https://steamcommunity.com/sharedfiles/filedetails/?id=2684501578).
