### ISSUE TITLE
A lot of whited out things

### ISSUE THREAD

**Issue by Temepest74** [ranaldsgift/ranalds.gift#6]
https://www.ranalds.gift/heroes/10/222322/32,1,3,6/19,1,5,7/3,2,1/1,5,1/3,2,3

**Comment by ranaldsgift** [comment]
Not sure what you mean, can you explain a little more?

**Comment by Temepest74** [comment]
![Screenshot_20221210_105508_Firefox.jpg](https://user-images.githubusercontent.com/28103890/206842144-4280f221-dfdb-4655-9cfd-5a9427dbb7b0.jpg)


This is on my phone, but it happens on pc as well. There are so many white icons. I think it is a bug

**Comment by ranaldsgift** [comment]
Okay yeah, thats definitely a bug lol. I'll look into it, thanks for reporting!

**Comment by ranaldsgift** [comment]
I couldn't reproduce the issue in chrome, firefox or edge. This looks like some type of CSS contrast/saturation filter being applied incorrectly to these elements. However there are only 2 instances of those types of filters in the app and they shouldn't apply here.

If I can reproduce the bug on my end it will be a lot easier to resolve. Either that or if you inspect the elements in your own browser, you may notice a filter being applied to the element. If you do, and you can screenshot the CSS that is being applied, this could also help resolve it.

**Comment by Temepest74** [comment]
Oh nvm, I was using an extension which broke your site. mb. Thank you
